using System.Collections.Generic;

namespace SilkTronPlugin;

public enum PlayerAnimationState
{
    Idle = 0,
    Airborne = 1,
    Land = 2,
    IdleToRun = 3,
    RunToIdle = 4,
    Turn = 5,
    WoundDoubleStrike = 6,
    Stun = 7,
    Recoil = 8,
    Dash = 9,
    Sprint = 10,
    DashToIdle = 11,
    SlashAlt = 12,
    SlashLandRunAlt = 13,
    DashAttackAntic = 14,
    SlashLand = 15,
    DashToRun = 16,
    UpSlash = 17,
    Slash = 18,
    DownSpikeAntic = 19,
    DownSpike = 20,
    DownspikeRecovery = 21,
    DownSpikeBounce2 = 22,
    DownSpikeBounce1 = 23,
    RecoilTwirl = 24,
    LandToRun = 25,
    SkidEnd1 = 26,
    HarpoonAntic = 27,
    HarpoonThrow = 28,
    HarpoonDash = 29,
    HarpoonCatch = 30,
    SilkChargeEnd = 31,
    AirDash = 32,
    SprintAir = 33,
    SprintAirLoop = 34,
    NeedleThrowAnticG = 35,
    NeedleThrowThrowing = 36,
    NeedleThrowCatch = 37,
    DoubleJump = 38,
    Walljump = 39,
    WallSlide = 40,
    DashAttack = 41,
    DashAttackRecover = 42,
    SlashToRun = 43,
    Run = 44,
    SkidEnd2 = 45,
    SprintAirShort = 46,
    MantleCling = 47,
    MantleVault = 48,
    SlashLandRun = 49,
    Wound = 50,
    HazardRespawn = 51,
    MantleLand = 52,
    MantleLandToRun = 53,
    SprintTurn = 54,
    NeedleThrowAnticA = 55,
    UmbrellaInflateAntic = 56,
    UmbrellaInflate = 57,
    UmbrellaFloat = 58,
    DownspikeRecoveryLand = 59,
    DashDown = 60,
    ShuttlecockAntic = 61,
    Shuttlecock = 62,
    SprintBackflip = 63,
    UmbrellaDeflate = 64,
    DashDownLand = 65,
    UmbrellaTurn = 66,
    MantleCancelToJump = 67,
    IdleHurt = 68,
    LookDown = 69,
    LookDownEnd = 70,
    LookUp = 71,
    LookUpEnd = 72,
    BindChargeGround = 73,
    BindBurstGround = 74,
    BindChargeAir = 75,
    BindBurstAir = 76,
    Fall = 77,
    WallCling = 78,
    WalljumpAntic = 79,
    HardLand = 80,
    Walk = 81,
    Unknown = 82
}

public static class PlayerAnimationMapper
{
    private static readonly Dictionary<string, PlayerAnimationState> AnimationMap = new()
    {
        { "Idle", PlayerAnimationState.Idle },
        { "Airborne", PlayerAnimationState.Airborne },
        { "Land", PlayerAnimationState.Land },
        { "Idle To Run", PlayerAnimationState.IdleToRun },
        { "Run To Idle", PlayerAnimationState.RunToIdle },
        { "Turn", PlayerAnimationState.Turn },
        { "Wound Double Strike", PlayerAnimationState.WoundDoubleStrike },
        { "Stun", PlayerAnimationState.Stun },
        { "Recoil", PlayerAnimationState.Recoil },
        { "Dash", PlayerAnimationState.Dash },
        { "Sprint", PlayerAnimationState.Sprint },
        { "Dash To Idle", PlayerAnimationState.DashToIdle },
        { "SlashAlt", PlayerAnimationState.SlashAlt },
        { "Slash Land Run Alt", PlayerAnimationState.SlashLandRunAlt },
        { "Dash Attack Antic", PlayerAnimationState.DashAttackAntic },
        { "Slash Land", PlayerAnimationState.SlashLand },
        { "Dash To Run", PlayerAnimationState.DashToRun },
        { "UpSlash", PlayerAnimationState.UpSlash },
        { "Slash", PlayerAnimationState.Slash },
        { "DownSpike Antic", PlayerAnimationState.DownSpikeAntic },
        { "DownSpike", PlayerAnimationState.DownSpike },
        { "Downspike Recovery", PlayerAnimationState.DownspikeRecovery },
        { "DownSpikeBounce 2", PlayerAnimationState.DownSpikeBounce2 },
        { "DownSpikeBounce 1", PlayerAnimationState.DownSpikeBounce1 },
        { "Recoil Twirl", PlayerAnimationState.RecoilTwirl },
        { "Land To Run", PlayerAnimationState.LandToRun },
        { "Skid End 1", PlayerAnimationState.SkidEnd1 },
        { "Harpoon Antic", PlayerAnimationState.HarpoonAntic },
        { "Harpoon Throw", PlayerAnimationState.HarpoonThrow },
        { "Harpoon Dash", PlayerAnimationState.HarpoonDash },
        { "Harpoon Catch", PlayerAnimationState.HarpoonCatch },
        { "Silk Charge End", PlayerAnimationState.SilkChargeEnd },
        { "Air Dash", PlayerAnimationState.AirDash },
        { "Sprint Air", PlayerAnimationState.SprintAir },
        { "Sprint Air Loop", PlayerAnimationState.SprintAirLoop },
        { "NeedleThrow AnticG", PlayerAnimationState.NeedleThrowAnticG },
        { "NeedleThrow Throwing", PlayerAnimationState.NeedleThrowThrowing },
        { "NeedleThrow Catch", PlayerAnimationState.NeedleThrowCatch },
        { "Double Jump", PlayerAnimationState.DoubleJump },
        { "Walljump", PlayerAnimationState.Walljump },
        { "Wall Slide", PlayerAnimationState.WallSlide },
        { "Dash Attack", PlayerAnimationState.DashAttack },
        { "Dash Attack Recover", PlayerAnimationState.DashAttackRecover },
        { "Slash To Run", PlayerAnimationState.SlashToRun },
        { "Run", PlayerAnimationState.Run },
        { "Skid End 2", PlayerAnimationState.SkidEnd2 },
        { "Sprint Air Short", PlayerAnimationState.SprintAirShort },
        { "Mantle Cling", PlayerAnimationState.MantleCling },
        { "Mantle Vault", PlayerAnimationState.MantleVault },
        { "Slash Land Run", PlayerAnimationState.SlashLandRun },
        { "Wound", PlayerAnimationState.Wound },
        { "Hazard Respawn", PlayerAnimationState.HazardRespawn },
        { "Mantle Land", PlayerAnimationState.MantleLand },
        { "Mantle Land To Run", PlayerAnimationState.MantleLandToRun },
        { "Sprint Turn", PlayerAnimationState.SprintTurn },
        { "NeedleThrow AnticA", PlayerAnimationState.NeedleThrowAnticA },
        { "Umbrella Inflate Antic", PlayerAnimationState.UmbrellaInflateAntic },
        { "Umbrella Inflate", PlayerAnimationState.UmbrellaInflate },
        { "Umbrella Float", PlayerAnimationState.UmbrellaFloat },
        { "Downspike Recovery Land", PlayerAnimationState.DownspikeRecoveryLand },
        { "Dash Down", PlayerAnimationState.DashDown },
        { "Shuttlecock Antic", PlayerAnimationState.ShuttlecockAntic },
        { "Shuttlecock", PlayerAnimationState.Shuttlecock },
        { "Sprint Backflip", PlayerAnimationState.SprintBackflip },
        { "Umbrella Deflate", PlayerAnimationState.UmbrellaDeflate },
        { "Dash Down Land", PlayerAnimationState.DashDownLand },
        { "Umbrella Turn", PlayerAnimationState.UmbrellaTurn },
        { "Mantle Cancel To Jump", PlayerAnimationState.MantleCancelToJump },
        { "Idle Hurt", PlayerAnimationState.IdleHurt },
        { "LookDown", PlayerAnimationState.LookDown },
        { "LookDownEnd", PlayerAnimationState.LookDownEnd },
        { "LookUp", PlayerAnimationState.LookUp },
        { "LookUpEnd", PlayerAnimationState.LookUpEnd },
        { "BindCharge Ground", PlayerAnimationState.BindChargeGround },
        { "BindBurst Ground", PlayerAnimationState.BindBurstGround },
        { "BindCharge Air", PlayerAnimationState.BindChargeAir },
        { "BindBurst Air", PlayerAnimationState.BindBurstAir },
        { "Fall", PlayerAnimationState.Fall },
        { "Wall Cling", PlayerAnimationState.WallCling },
        { "Walljump Antic", PlayerAnimationState.WalljumpAntic },
        { "HardLand", PlayerAnimationState.HardLand },
        { "Walk", PlayerAnimationState.Walk },
    };

    public static PlayerAnimationState GetAnimationState(string clipName)
    {
        if (string.IsNullOrEmpty(clipName))
            return PlayerAnimationState.Unknown;

        return AnimationMap.TryGetValue(clipName, out var state) ? state : PlayerAnimationState.Unknown;
    }
}