PLAYER_MAX_HEALTH = 9
PLAYER_MAX_SILK = 12

BOSS_MAX_PHASE = 2

MAX_EPISODE_STEPS = 2000

# Game time per env step: Constants.FramesPerStep (2) * Time.fixedDeltaTime (0.02) in the plugin.
STEP_DURATION_SECONDS = 0.04

NUM_RAYS = 32
NUM_HIT_TYPES = 6
RAYCAST_DIM = NUM_RAYS * 2

NUM_BOSS_ANIMATION_STATES = 103
NUM_PLAYER_ANIMATION_STATES = 83

STATE_DIM = 25
OBSERVATION_DIM = STATE_DIM + RAYCAST_DIM

HERO_VEL_X_RANGE = (-70.0, 70.0)
HERO_VEL_Y_RANGE = (-35.0, 22.0)
